Added smoke tests for all JREs (#304)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -170,14 +170,14 @@ code_coverage_steps: &code_coverage_steps
     # Download and cache dependencies
     - restore_cache:
         keys:
-          - v1-dependencies-{{ checksum "build.gradle" }}
+          - v2-dependencies-{{ checksum "conf/gradle/dependencies.gradle" }}
           # fallback to using the latest cache if no exact match is found
-          - v1-dependencies-
+          - v2-dependencies-
 
     - save_cache:
         paths:
           - ~/.gradle
-        key: v1-dependencies-{{ checksum "build.gradle" }}
+        key: v2-dependencies-{{ checksum "conf/gradle/dependencies.gradle" }}
 
     - run:
         name: Run JaCoCo plugin code coverage
@@ -229,21 +229,61 @@ smoke_test_in_docker_compose_steps: &smoke_test_in_docker_compose_steps
 
     - run:
         # ubuntu-2004:202107-02 uses 'ash' shell, not 'bash'
-        name: Make cURL request to the stubby4j container
+        name: Make cURL request to the stubby4j JRE 8 container
         command: |
           sleep 1
           smoke_test_response=$(docker run \
-            --network container:stubby4j_service appropriate/curl \
+            --network container:stubby4j_jre8 appropriate/curl \
             --retry 10 --retry-delay 1 --retry-connrefused --silent  \
             -X GET -H "Content-Type: application/json" \
             http://localhost:8882/tests/smoke-test/1)
 
           if [ "$smoke_test_response" != "OK" ]
           then
-            echo "Got response $smoke_test_response from stubby4j container, failing ... "
+            echo "Got response $smoke_test_response from stubby4j JRE 8 container, failing ... "
             exit 1
           else
-            echo "Smoke tests passed!"
+            echo "stubby4j JRE 8 smoke tests passed!"
+            exit 0
+          fi
+
+    - run:
+        # ubuntu-2004:202107-02 uses 'ash' shell, not 'bash'
+        name: Make cURL request to the stubby4j JRE 11 container
+        command: |
+          sleep 1
+          smoke_test_response=$(docker run \
+            --network container:stubby4j_jre11 appropriate/curl \
+            --retry 10 --retry-delay 1 --retry-connrefused --silent  \
+            -X GET -H "Content-Type: application/json" \
+            http://localhost:8883/tests/smoke-test/1)
+
+          if [ "$smoke_test_response" != "OK" ]
+          then
+            echo "Got response $smoke_test_response from stubby4j JRE 11 container, failing ... "
+            exit 1
+          else
+            echo "stubby4j JRE 11 smoke tests passed!"
+            exit 0
+          fi
+
+    - run:
+        # ubuntu-2004:202107-02 uses 'ash' shell, not 'bash'
+        name: Make cURL request to the stubby4j JRE 16 container
+        command: |
+          sleep 1
+          smoke_test_response=$(docker run \
+            --network container:stubby4j_jre16 appropriate/curl \
+            --retry 10 --retry-delay 1 --retry-connrefused --silent  \
+            -X GET -H "Content-Type: application/json" \
+            http://localhost:8884/tests/smoke-test/1)
+
+          if [ "$smoke_test_response" != "OK" ]
+          then
+            echo "Got response $smoke_test_response from stubby4j JRE 16 container, failing ... "
+            exit 1
+          else
+            echo "stubby4j JRE 16 smoke tests passed!"
             exit 0
           fi
 
@@ -343,7 +383,7 @@ workflows:
           <<: *filter_ignore_master
 
 
-  branch-jdk15:
+  branch-jdk16:
     jobs:
       - gradle_7_0_2_jdk16:
           <<: *filter_ignore_master
